### ISSUE TITLE
Two PMIR RelatedPerson StructureDefinitions

### ISSUE THREAD

**Issue by lynnfel** [IHE/fhir#53]
Luke

There are currently two PMIR RelatedPerson StructureDefinitions in https://github.com/IHE/fhir/tree/master/StructureDefinition.  You can remove the out-of-date file.

thx

**Comment by lukeaduncan** [comment]
I only see one for Patient being linked to the RelatedPerson (structuredefinition-IHE.PMIR.Patient.RelatedPerson.xml) and then the RelatedPerson (structuredefinition-IHE.PMIR.RelatedPerson.xml) itself.

**Comment by lynnfel** [comment]
I didn't look closely enough at the difference between the two files.  I'm closing the issue.
