### ISSUE TITLE
We should consistenly use 'date'  in our StructureDefinitions

### ISSUE THREAD

**Issue by lynnfel** [IHE/fhir#54]
I am currently working with the Gazelle team to find out which StructureDefinitions they currently have loaded on the Gazelle EVSClient.

In EVSClient, the user initiating a validation request is presented with a dropdown list of StructureDefinitions (under a pseudonym), but I (as a user) have no idea what validation is being applied.  

The opaqueness of Gazelle EVSClient is not the purpose of this issue, *but* if we (ITI / IHE) put consistently update the 'date' field in our StructureDefintions, I can ask Gazelle EVSClient to use that.   I have not looked at all StructureDefinitions, but I did find at least one with a version and no date, and there is a newly update PMIR StructureDefin9tion that has a 2019 date https://github.com/IHE/fhir/blob/master/StructureDefinition/structuredefinition-IHE.PMIR.RelatedPerson.xml

For reference, I have submitted a separate Jira issue for the Gazelle EVSClient to use this information when they are doing FHIR validations with our StructureDefinitions.  See https://gazelle.ihe.net/jira/browse/EVSCLT-843.

**Comment by JohnMoehrke** [comment]
I had not recommended version, as that would have required us to come up with a meaning to our version methodology. I have been recommending that the .date element must be populated with a proper date of when it was released. And that should always be an increasing date, without revisiting history. Can you get them to use the date element?

**Comment by oliveregger** [comment]
I think the versioning should be done on the implementation guide level, and the validation request and the response should indicate which StructureDefinition and implementation guide version should be used with the pipe syntax.

**Comment by lynnfel** [comment]
I will try to ask for date.

**Comment by JohnMoehrke** [comment]
closing due to our move to IG publisher, and consistency driven there.
