### ISSUE TITLE
Consistent naming of StructureDefinitions will help presentation in Gazelle EVSClient

### ISSUE THREAD

**Issue by lynnfel** [IHE/fhir#55]
![1](https://user-images.githubusercontent.com/47753616/104231672-ed2a8d00-5414-11eb-86c5-d2907df855a6.jpg)
The Gazelle EVSClient tool uses the StructureDefinitions published by IHE in GitHub as part of the FHIR Validation.

The tool offers a dropdown list that is 'related' to the StructureDefinition files.   The problem
is that the  current list does not enable a user like me to know how a list entry in EVSClient maps to the StructureDefinition list in https://github.com/IHE/fhir/tree/master/StructureDefinition

See screen shot for a subset of the EVSClient list.

I don't know whether naming convention is the answer, but I am submitting this issue to figure out a solution.

**Comment by costateixeira** [comment]
A naming convention would be necessary
Additionally (and perhaps better), perhaps this display name would be an additional property in the StructureDefinition.
We started capturing a model for our artifacts, and StructureDefinitions is one of those artifacts

**Comment by litlfred** [comment]
I would definitely be supportive of this as it would (also) address some
issues that I have encountered in the past when trying to make linkages
between IGs.   On a related note, it would be great to see this applied to
compliance statements as well as something similar for actors.  This also
raises the issue of having consistent section numbering in IG's to make the
cross IG references easier to compute.


Cheers,
-carl

**Comment by lynnfel** [comment]
Note that the 'solution' is probably partly done by IHE, and partly done in the Gazelle EVSClient (I have a separate/related issue submitted there).   In the end, the user wants to know whether the StructureDefinition in EVSClient is the current one published by IHE.   If EVSClient allowed a user to see the StructureDefinition, that would help.   If IHE consistently used version or date or some other element in the StructureDefinition, that would help.    

I did not mean to imply that naming convention was the right or only solution.

**Comment by costateixeira** [comment]
The naming convention AND a structured way of using the different names seems useful.
Besides, it is machine-enforceable, so I think it is something to work towards

**Comment by JohnMoehrke** [comment]
we do have guidance on the naming ...  https://wiki.ihe.net/index.php/Guidance_on_writing_Profiles_of_FHIR

but we have no mecahnism to force the naming.

and many are not even caught up to the R4 guidance.

**Comment by lynnfel** [comment]
Thanks John.  The wiki page you refer to contains more than guidance on name.  The StructureDefinition section has guidance on use of many elements (https://wiki.ihe.net/index.php/Guidance_on_writing_Profiles_of_FHIR#StructureDefinition_-_content_recommendation).  

If I go back to my original problem (how to identify structure definitions in an EVSClient dropdown list), if I asked the Gazelle team to use a combination of id and date, then I (as an EVSClient user) could determine whether the tool has the latest StructureDefinition published by IHE in GitHub.
