### ISSUE TITLE
IHE_SecurityTypes_codesystem is not a valid FHIR ID

### ISSUE THREAD

**Issue by lynnfel** [IHE/fhir#56]
I tried adding our Security Types code system to the HAPI FHIR Server we used for CAT testing and got:

 Warning!

Error: HTTP 400 : Can not process entity with ID[IHE_SecurityTypes_codesystem], this is not a valid FHIR ID

**Comment by JohnMoehrke** [comment]
yes, "_" is not allowed. Need to change them to "." . Can you test that solution with your system?

**Comment by lynnfel** [comment]
yes.  "." works

**Comment by JohnMoehrke** [comment]
I fixed the version on github
